FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y && apt-get install -y cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev
RUN apt-get install -f
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN source ~/.cargo/env
RUN rustup default stable
RUN rustup update nightly && rustup target add wasm32-unknown-unknown --toolchain nightly