FROM ubuntu:latest

RUN apt update && apt install curl python python3 -qq -y
RUN curl -fsSL https://raw.githubusercontent.com/paritytech/scripts/a5522fbf583e058c001604c473f9516f87650b4e/wasm-utils/install-rust-lld-ARM.sh | bash
ADD . /mynachain
WORKDIR /mynachain
RUN cargo build --release